platform :ios , '7.0'
pod 'Shimmer'
pod 'RNRippleTableView', '~> 0.1.4'
pod 'HMSideMenu', '~> 1.1.0'
pod 'EAIntroView', '~> 2.3.1'
pod 'MJPopupViewController', '~> 0.4'
pod 'iCarousel', '~> 1.7.6'
pod 'SIAlertView', '~> 1.3'
pod 'JASidePanels', '~> 1.3.2'
pod 'JSMessagesViewController', '~> 4.0.2'
pod 'RNFrostedSidebar', '~> 0.2.0'
pod 'MSDynamicsDrawerViewController'
pod 'Canvas'
pod 'FRDLivelyButton', '~> 1.1.2'
pod 'MKMapView-ZoomLevel', '~> 1.1.0'
pod 'RNGridMenu', '~> 0.1.3'
pod 'ALRadial', '~> 0.1.0'
pod 'DropdownMenu'
pod 'CFShareCircle', '~> 1.0.0'